#!/bin/bash
# this file should be located in the library, while the source files should be located in the appropriate subdirectory "LPDC-TannerGraphs" within the library

cd ./LDPC-TannerGraphs


# obtain argument list
args="$*"

eval "python3 Main.py $args"

cexecutable="$(cat ./transfer.txt)"

cd ..
eval "$cexecutable"
