#!/bin/bash
# this file should be located in the library, while the source files should be located in a subdirectory within the library

# compile all java source files
THE_CLASSPATH=
PROGRAM_NAME=MakePCHK.java
cd ./LinearCodes/src

for i in `ls ./`
    do
    THE_CLASSPATH=${THE_CLASSPATH}:${i}
done

javac -classpath ".:${THE_CLASSPATH}" $PROGRAM_NAME

# if [ $? -eq 0 ]
# then
#     echo "source files successfully compiled"
# fi

# obtain argument list
args="$*"

eval "java MakePCHK $args"

cexecutable="$(cat ./transfer.txt)"

cd ..
cd ..
eval "$cexecutable"

